-- if key == "space" then
-- 		if
-- 			not game_state.current_fish
-- 			and #game_state.pond > 0
-- 			and game_state.bait_left > 0
-- 			and #game_state.fish_caught_this_round < 5
-- 		then
-- 			game_state.current_fish, game_state.bait_left = game.catch_fish(game_state.pond, game_state.bait_left)
-- 			game_state.status_text = (
-- 				"You caught a "
-- 				.. game_state.current_fish.name
-- 				.. "!\nDo you wnat to keep it? (Y/n)"
-- 			)
-- 		elseif #game_state.pond == 0 then
-- 			print("You lost :(")
-- 		elseif game_state.bait_left == 0 then
-- 			print("Out of bait")
-- 		end
-- 	end

-- 	if key == "y" then
-- 		if game_state.current_fish then
-- 			-- print("Fish caught!")
-- 			game_state.fish_caught_this_round[#game_state.fish_caught_this_round + 1] = game_state.current_fish
-- 		end

-- 		game_state.current_fish = false
-- 		game_state.status_text = "Press space to catch a fish"
-- 		if game_state.bait_left == 0 then
-- 			game_state.state = "shop"
-- 		end
-- 	end

-- 	if key == "n" then
-- 		if game_state.current_fish then
-- 			-- print("Fish released!")
-- 			game_state.fish_released_this_round[#game_state.fish_released_this_round + 1] = game_state.current_fish
-- 		end

-- 		game_state.current_fish = false
-- 		game_state.status_text = "Press space to catch a fish"
-- 		if game_state.bait_left == 0 then
-- 			game_state.state = "shop"
-- 		end
-- 	end

-- 	if key == "return" then
-- 		if game_state.state == "shop" then
-- 			game.end_round(rng)
-- 		end
-- 	end
