-- Species ranges are typical game-sized fish, not species maxima.
---@type table<string, FishSpecies>
local fish_species = {
	common_carp = {
		name = "Common Carp",
		min_length = 25,
		max_length = 55,
		girth_ratio = 0.75,
		factor = 25000,
		base_price = 0.5,
		multiplier = 1,
		rarity = 1,
		sprite_index = 1,
	},
	pacific_sardine = {
		name = "Pacific Sardine",
		min_length = 18,
		max_length = 25,
		girth_ratio = 0.62,
		factor = 21000,
		base_price = 0.75,
		multiplier = 1,
		rarity = 1,
		sprite_index = 2,
	},
	atlantic_herring = {
		name = "Atlantic Herring",
		min_length = 25,
		max_length = 35,
		girth_ratio = 0.55,
		factor = 27000,
		base_price = 0.75,
		multiplier = 1,
		rarity = 1,
		sprite_index = 3,
	},
	lanternfish = {
		name = "Lanternfish",
		min_length = 5,
		max_length = 15,
		girth_ratio = 0.50,
		factor = 24000,
		base_price = 0.75,
		multiplier = 1,
		rarity = 4,
		sprite_index = 4,
	},
	atlantic_cod = {
		name = "Atlantic Cod",
		min_length = 35,
		max_length = 100,
		girth_ratio = 0.63,
		factor = 28000,
		base_price = 0.75,
		multiplier = 1,
		rarity = 2,
		sprite_index = 5,
	},
	bluefish = {
		name = "Bluefish",
		min_length = 35,
		max_length = 90,
		girth_ratio = 0.64,
		factor = 28000,
		base_price = 0.75,
		multiplier = 1,
		rarity = 3,
		sprite_index = 6,
	},
	tuna = {
		name = "Tuna",
		min_length = 40,
		max_length = 115,
		girth_ratio = 0.72,
		factor = 28000,
		base_price = 0.75,
		multiplier = 1,
		rarity = 3,
		sprite_index = 7,
	},
}

return fish_species
